// GENERATED. Do not edit by hand.
//
// Each laddered problem paired with the Saintly topic article that best matches
// it. Every one was judged from the problem statement rather than from our
// subject tags, which only distinguish Algebra / Geometry / Number Theory /
// Combinatorics and cannot tell similar triangles from trigonometry.
//
// Only confident matches are here. Problems whose best match was weak, and the
// 78 with no reasonable article at all, are absent, and the button does not
// render for them. Sending someone who is already stuck to a page that does not
// address their problem is worse than showing nothing.
//
// Tuples rather than objects to keep the bundle small: 207 entries.
const LINKS: Record<string, [topic: string, url: string]> = {
  "2020-aime-i-10": ["Prime Factorization", "https://saintlymath.com/prime%20factorization.html"],
  "2020-aime-i-11": ["Functions And Graphing", "https://saintlymath.com/functions%20and%20graphing.html"],
  "2020-aime-i-12": ["Modular Arithmetic", "https://saintlymath.com/modular%20arithmetic.html"],
  "2020-aime-i-14": ["Functions And Graphing", "https://saintlymath.com/functions%20and%20graphing.html"],
  "2020-aime-i-2": ["Series", "https://saintlymath.com/series.html"],
  "2020-aime-i-4": ["Prime Factorization", "https://saintlymath.com/prime%20factorization.html"],
  "2020-aime-i-5": ["Casework", "https://saintlymath.com/casework.html"],
  "2020-aime-i-7": ["Counting", "https://saintlymath.com/counting.html"],
  "2020-aime-i-8": ["Series", "https://saintlymath.com/series.html"],
  "2020-aime-i-9": ["Prime Factorization", "https://saintlymath.com/prime%20factorization.html"],
  "2020-aime-ii-1": ["Prime Factorization", "https://saintlymath.com/prime%20factorization.html"],
  "2020-aime-ii-10": ["Modular Arithmetic", "https://saintlymath.com/modular%20arithmetic.html"],
  "2020-aime-ii-11": ["Functions And Graphing", "https://saintlymath.com/functions%20and%20graphing.html"],
  "2020-aime-ii-12": ["Systems Of Equations", "https://saintlymath.com/systems%20of%20equations.html"],
  "2020-aime-ii-2": ["Functions And Graphing", "https://saintlymath.com/functions%20and%20graphing.html"],
  "2020-aime-ii-3": ["Exponents", "https://saintlymath.com/exponents.html"],
  "2020-aime-ii-4": ["Transformations", "https://saintlymath.com/transformations.html"],
  "2020-aime-ii-8": ["Absolute Value", "https://saintlymath.com/absolute%20value.html"],
  "2020-aime-ii-9": ["Counting", "https://saintlymath.com/counting.html"],
  "2021-aime-i-1": ["Casework", "https://saintlymath.com/casework.html"],
  "2021-aime-i-11": ["Similar Triangles", "https://saintlymath.com/similar%20triangles.html"],
  "2021-aime-i-14": ["Modular Arithmetic", "https://saintlymath.com/modular%20arithmetic.html"],
  "2021-aime-i-15": ["Functions And Graphing", "https://saintlymath.com/functions%20and%20graphing.html"],
  "2021-aime-i-3": ["Exponents", "https://saintlymath.com/exponents.html"],
  "2021-aime-i-4": ["Counting", "https://saintlymath.com/counting.html"],
  "2021-aime-i-5": ["Series", "https://saintlymath.com/series.html"],
  "2021-aime-i-7": ["Trigonometry", "https://saintlymath.com/trigonometry.html"],
  "2021-aime-i-8": ["Absolute Value", "https://saintlymath.com/absolute%20value.html"],
  "2021-aime-ii-1": ["Averages", "https://saintlymath.com/averages.html"],
  "2021-aime-ii-12": ["Trigonometry", "https://saintlymath.com/trigonometry.html"],
  "2021-aime-ii-13": ["Modular Arithmetic", "https://saintlymath.com/modular%20arithmetic.html"],
  "2021-aime-ii-2": ["Similar Triangles", "https://saintlymath.com/similar%20triangles.html"],
  "2021-aime-ii-3": ["Modular Arithmetic", "https://saintlymath.com/modular%20arithmetic.html"],
  "2021-aime-ii-4": ["Functions And Graphing", "https://saintlymath.com/functions%20and%20graphing.html"],
  "2021-aime-ii-5": ["Trigonometry", "https://saintlymath.com/trigonometry.html"],
  "2021-aime-ii-6": ["Counting", "https://saintlymath.com/counting.html"],
  "2021-aime-ii-7": ["Factoring", "https://saintlymath.com/factoring.html"],
  "2021-aime-ii-9": ["Modular Arithmetic", "https://saintlymath.com/modular%20arithmetic.html"],
  "2022-aime-i-1": ["Functions And Graphing", "https://saintlymath.com/functions%20and%20graphing.html"],
  "2022-aime-i-12": ["Counting", "https://saintlymath.com/counting.html"],
  "2022-aime-i-13": ["Prime Factorization", "https://saintlymath.com/prime%20factorization.html"],
  "2022-aime-i-15": ["Systems Of Equations", "https://saintlymath.com/systems%20of%20equations.html"],
  "2022-aime-i-4": ["Modular Arithmetic", "https://saintlymath.com/modular%20arithmetic.html"],
  "2022-aime-i-5": ["Speed-Distance-Time", "https://saintlymath.com/speed-distance-time.html"],
  "2022-aime-i-6": ["Casework", "https://saintlymath.com/casework.html"],
  "2022-aime-i-9": ["Counting", "https://saintlymath.com/counting.html"],
  "2022-aime-ii-1": ["Systems Of Equations", "https://saintlymath.com/systems%20of%20equations.html"],
  "2022-aime-ii-10": ["Modular Arithmetic", "https://saintlymath.com/modular%20arithmetic.html"],
  "2022-aime-ii-2": ["Casework", "https://saintlymath.com/casework.html"],
  "2022-aime-ii-4": ["Exponents", "https://saintlymath.com/exponents.html"],
  "2022-aime-ii-5": ["Counting", "https://saintlymath.com/counting.html"],
  "2022-aime-ii-6": ["Absolute Value", "https://saintlymath.com/absolute%20value.html"],
  "2022-aime-ii-7": ["Similar Triangles", "https://saintlymath.com/similar%20triangles.html"],
  "2022-aime-ii-8": ["Modular Arithmetic", "https://saintlymath.com/modular%20arithmetic.html"],
  "2022-aime-ii-9": ["Counting", "https://saintlymath.com/counting.html"],
  "2022-amc-10a-22": ["Counting", "https://saintlymath.com/counting.html"],
  "2022-amc-10a-24": ["Casework", "https://saintlymath.com/casework.html"],
  "2022-amc-10b-21": ["Functions And Graphing", "https://saintlymath.com/functions%20and%20graphing.html"],
  "2022-amc-10b-24": ["Absolute Value", "https://saintlymath.com/absolute%20value.html"],
  "2022-amc-10b-25": ["Modular Arithmetic", "https://saintlymath.com/modular%20arithmetic.html"],
  "2022-amc-12a-21": ["Factoring", "https://saintlymath.com/factoring.html"],
  "2022-amc-12a-23": ["Prime Factorization", "https://saintlymath.com/prime%20factorization.html"],
  "2022-amc-12a-24": ["Casework", "https://saintlymath.com/casework.html"],
  "2022-amc-12b-23": ["Modular Arithmetic", "https://saintlymath.com/modular%20arithmetic.html"],
  "2022-amc-12b-24": ["Trigonometry", "https://saintlymath.com/trigonometry.html"],
  "2023-aime-i-1": ["Counting", "https://saintlymath.com/counting.html"],
  "2023-aime-i-11": ["Counting", "https://saintlymath.com/counting.html"],
  "2023-aime-i-12": ["Trigonometry", "https://saintlymath.com/trigonometry.html"],
  "2023-aime-i-2": ["Exponents", "https://saintlymath.com/exponents.html"],
  "2023-aime-i-3": ["Counting", "https://saintlymath.com/counting.html"],
  "2023-aime-i-4": ["Prime Factorization", "https://saintlymath.com/prime%20factorization.html"],
  "2023-aime-i-6": ["Casework", "https://saintlymath.com/casework.html"],
  "2023-aime-i-7": ["Modular Arithmetic", "https://saintlymath.com/modular%20arithmetic.html"],
  "2023-aime-i-9": ["Functions And Graphing", "https://saintlymath.com/functions%20and%20graphing.html"],
  "2023-aime-ii-1": ["Series", "https://saintlymath.com/series.html"],
  "2023-aime-ii-10": ["Modular Arithmetic", "https://saintlymath.com/modular%20arithmetic.html"],
  "2023-aime-ii-11": ["Counting", "https://saintlymath.com/counting.html"],
  "2023-aime-ii-13": ["Trigonometry", "https://saintlymath.com/trigonometry.html"],
  "2023-aime-ii-15": ["Modular Arithmetic", "https://saintlymath.com/modular%20arithmetic.html"],
  "2023-aime-ii-3": ["Trigonometry", "https://saintlymath.com/trigonometry.html"],
  "2023-aime-ii-4": ["Systems Of Equations", "https://saintlymath.com/systems%20of%20equations.html"],
  "2023-aime-ii-5": ["Prime Factorization", "https://saintlymath.com/prime%20factorization.html"],
  "2023-aime-ii-7": ["Casework", "https://saintlymath.com/casework.html"],
  "2023-aime-ii-8": ["Factoring", "https://saintlymath.com/factoring.html"],
  "2023-aime-ii-9": ["Similar Triangles", "https://saintlymath.com/similar%20triangles.html"],
  "2023-amc-10a-21": ["Functions And Graphing", "https://saintlymath.com/functions%20and%20graphing.html"],
  "2023-amc-10a-23": ["Prime Factorization", "https://saintlymath.com/prime%20factorization.html"],
  "2023-amc-10b-23": ["Series", "https://saintlymath.com/series.html"],
  "2023-amc-10b-24": ["Transformations", "https://saintlymath.com/transformations.html"],
  "2023-amc-12a-22": ["Prime Factorization", "https://saintlymath.com/prime%20factorization.html"],
  "2023-amc-12a-23": ["Inequalities", "https://saintlymath.com/inequalities.html"],
  "2023-amc-12a-24": ["Counting", "https://saintlymath.com/counting.html"],
  "2023-amc-12a-25": ["Trigonometry", "https://saintlymath.com/trigonometry.html"],
  "2023-amc-12b-22": ["Functions And Graphing", "https://saintlymath.com/functions%20and%20graphing.html"],
  "2023-amc-12b-23": ["Prime Factorization", "https://saintlymath.com/prime%20factorization.html"],
  "2023-amc-12b-24": ["Prime Factorization", "https://saintlymath.com/prime%20factorization.html"],
  "2024-aime-i-1": ["Speed-Distance-Time", "https://saintlymath.com/speed-distance-time.html"],
  "2024-aime-i-11": ["Casework", "https://saintlymath.com/casework.html"],
  "2024-aime-i-12": ["Absolute Value", "https://saintlymath.com/absolute%20value.html"],
  "2024-aime-i-13": ["Modular Arithmetic", "https://saintlymath.com/modular%20arithmetic.html"],
  "2024-aime-i-2": ["Exponents", "https://saintlymath.com/exponents.html"],
  "2024-aime-i-4": ["Counting", "https://saintlymath.com/counting.html"],
  "2024-aime-i-6": ["Counting", "https://saintlymath.com/counting.html"],
  "2024-aime-i-7": ["Trigonometry", "https://saintlymath.com/trigonometry.html"],
  "2024-aime-i-8": ["Similar Triangles", "https://saintlymath.com/similar%20triangles.html"],
  "2024-aime-i-9": ["Functions And Graphing", "https://saintlymath.com/functions%20and%20graphing.html"],
  "2024-aime-ii-1": ["Counting", "https://saintlymath.com/counting.html"],
  "2024-aime-ii-11": ["Factoring", "https://saintlymath.com/factoring.html"],
  "2024-aime-ii-13": ["Factoring", "https://saintlymath.com/factoring.html"],
  "2024-aime-ii-15": ["Counting", "https://saintlymath.com/counting.html"],
  "2024-aime-ii-2": ["Averages", "https://saintlymath.com/averages.html"],
  "2024-aime-ii-3": ["Casework", "https://saintlymath.com/casework.html"],
  "2024-aime-ii-4": ["Systems Of Equations", "https://saintlymath.com/systems%20of%20equations.html"],
  "2024-aime-ii-5": ["Similar Triangles", "https://saintlymath.com/similar%20triangles.html"],
  "2024-aime-ii-6": ["Counting", "https://saintlymath.com/counting.html"],
  "2024-aime-ii-7": ["Modular Arithmetic", "https://saintlymath.com/modular%20arithmetic.html"],
  "2024-aime-ii-9": ["Counting", "https://saintlymath.com/counting.html"],
  "2024-amc-10a-10": ["Modular Arithmetic", "https://saintlymath.com/modular%20arithmetic.html"],
  "2024-amc-10a-11": ["Factoring", "https://saintlymath.com/factoring.html"],
  "2024-amc-10a-12": ["Averages", "https://saintlymath.com/averages.html"],
  "2024-amc-10a-13": ["Transformations", "https://saintlymath.com/transformations.html"],
  "2024-amc-10a-15": ["Factoring", "https://saintlymath.com/factoring.html"],
  "2024-amc-10a-16": ["Similar Triangles", "https://saintlymath.com/similar%20triangles.html"],
  "2024-amc-10a-17": ["Casework", "https://saintlymath.com/casework.html"],
  "2024-amc-10a-18": ["Modular Arithmetic", "https://saintlymath.com/modular%20arithmetic.html"],
  "2024-amc-10a-19": ["Series", "https://saintlymath.com/series.html"],
  "2024-amc-10a-2": ["Systems Of Equations", "https://saintlymath.com/systems%20of%20equations.html"],
  "2024-amc-10a-20": ["Casework", "https://saintlymath.com/casework.html"],
  "2024-amc-10a-21": ["Series", "https://saintlymath.com/series.html"],
  "2024-amc-10a-23": ["Systems Of Equations", "https://saintlymath.com/systems%20of%20equations.html"],
  "2024-amc-10a-3": ["Prime Factorization", "https://saintlymath.com/prime%20factorization.html"],
  "2024-amc-10a-5": ["Prime Factorization", "https://saintlymath.com/prime%20factorization.html"],
  "2024-amc-10a-6": ["Counting", "https://saintlymath.com/counting.html"],
  "2024-amc-10a-7": ["Prime Factorization", "https://saintlymath.com/prime%20factorization.html"],
  "2024-amc-10a-8": ["Speed-Distance-Time", "https://saintlymath.com/speed-distance-time.html"],
  "2024-amc-10a-9": ["Counting", "https://saintlymath.com/counting.html"],
  "2024-amc-10b-22": ["Counting", "https://saintlymath.com/counting.html"],
  "2024-amc-10b-23": ["Series", "https://saintlymath.com/series.html"],
  "2024-amc-10b-24": ["Modular Arithmetic", "https://saintlymath.com/modular%20arithmetic.html"],
  "2024-amc-12a-21": ["Series", "https://saintlymath.com/series.html"],
  "2024-amc-12a-23": ["Trigonometry", "https://saintlymath.com/trigonometry.html"],
  "2024-amc-12a-25": ["Functions And Graphing", "https://saintlymath.com/functions%20and%20graphing.html"],
  "2024-amc-12b-21": ["Trigonometry", "https://saintlymath.com/trigonometry.html"],
  "2024-amc-12b-22": ["Trigonometry", "https://saintlymath.com/trigonometry.html"],
  "2024-amc-12b-25": ["Casework", "https://saintlymath.com/casework.html"],
  "2025-aime-i-10": ["Casework", "https://saintlymath.com/casework.html"],
  "2025-aime-i-11": ["Functions And Graphing", "https://saintlymath.com/functions%20and%20graphing.html"],
  "2025-aime-i-12": ["Inequalities", "https://saintlymath.com/inequalities.html"],
  "2025-aime-i-13": ["Counting", "https://saintlymath.com/counting.html"],
  "2025-aime-i-14": ["Trigonometry", "https://saintlymath.com/trigonometry.html"],
  "2025-aime-i-15": ["Modular Arithmetic", "https://saintlymath.com/modular%20arithmetic.html"],
  "2025-aime-i-2": ["Transformations", "https://saintlymath.com/transformations.html"],
  "2025-aime-i-3": ["Casework", "https://saintlymath.com/casework.html"],
  "2025-aime-i-4": ["Factoring", "https://saintlymath.com/factoring.html"],
  "2025-aime-i-5": ["Modular Arithmetic", "https://saintlymath.com/modular%20arithmetic.html"],
  "2025-aime-i-7": ["Casework", "https://saintlymath.com/casework.html"],
  "2025-aime-i-8": ["Functions And Graphing", "https://saintlymath.com/functions%20and%20graphing.html"],
  "2025-aime-i-9": ["Transformations", "https://saintlymath.com/transformations.html"],
  "2025-aime-ii-10": ["Counting", "https://saintlymath.com/counting.html"],
  "2025-aime-ii-11": ["Counting", "https://saintlymath.com/counting.html"],
  "2025-aime-ii-12": ["Trigonometry", "https://saintlymath.com/trigonometry.html"],
  "2025-aime-ii-14": ["Trigonometry", "https://saintlymath.com/trigonometry.html"],
  "2025-aime-ii-15": ["Functions And Graphing", "https://saintlymath.com/functions%20and%20graphing.html"],
  "2025-aime-ii-2": ["Modular Arithmetic", "https://saintlymath.com/modular%20arithmetic.html"],
  "2025-aime-ii-3": ["Casework", "https://saintlymath.com/casework.html"],
  "2025-aime-ii-4": ["Exponents", "https://saintlymath.com/exponents.html"],
  "2025-aime-ii-7": ["Prime Factorization", "https://saintlymath.com/prime%20factorization.html"],
  "2025-aime-ii-8": ["Casework", "https://saintlymath.com/casework.html"],
  "2025-aime-ii-9": ["Trigonometry", "https://saintlymath.com/trigonometry.html"],
  "2025-amc-10a-21": ["Counting", "https://saintlymath.com/counting.html"],
  "2025-amc-10a-23": ["Similar Triangles", "https://saintlymath.com/similar%20triangles.html"],
  "2025-amc-10a-24": ["Casework", "https://saintlymath.com/casework.html"],
  "2025-amc-10b-21": ["Casework", "https://saintlymath.com/casework.html"],
  "2025-amc-10b-22": ["Modular Arithmetic", "https://saintlymath.com/modular%20arithmetic.html"],
  "2025-amc-10b-23": ["Modular Arithmetic", "https://saintlymath.com/modular%20arithmetic.html"],
  "2025-amc-10b-25": ["Transformations", "https://saintlymath.com/transformations.html"],
  "2025-amc-12a-21": ["Series", "https://saintlymath.com/series.html"],
  "2025-amc-12a-23": ["Casework", "https://saintlymath.com/casework.html"],
  "2025-amc-12a-24": ["Trigonometry", "https://saintlymath.com/trigonometry.html"],
  "2025-amc-12a-25": ["Functions And Graphing", "https://saintlymath.com/functions%20and%20graphing.html"],
  "2025-amc-12b-21": ["Trigonometry", "https://saintlymath.com/trigonometry.html"],
  "2025-amc-12b-22": ["Transformations", "https://saintlymath.com/transformations.html"],
  "2025-amc-12b-23": ["Modular Arithmetic", "https://saintlymath.com/modular%20arithmetic.html"],
  "2025-amc-12b-24": ["Functions And Graphing", "https://saintlymath.com/functions%20and%20graphing.html"],
  "2025-amc-12b-25": ["Trigonometry", "https://saintlymath.com/trigonometry.html"],
  "2026-aime-i-1": ["Speed-Distance-Time", "https://saintlymath.com/speed-distance-time.html"],
  "2026-aime-i-10": ["Transformations", "https://saintlymath.com/transformations.html"],
  "2026-aime-i-11": ["Absolute Value", "https://saintlymath.com/absolute%20value.html"],
  "2026-aime-i-13": ["Modular Arithmetic", "https://saintlymath.com/modular%20arithmetic.html"],
  "2026-aime-i-2": ["Counting", "https://saintlymath.com/counting.html"],
  "2026-aime-i-4": ["Factoring", "https://saintlymath.com/factoring.html"],
  "2026-aime-i-5": ["Trigonometry", "https://saintlymath.com/trigonometry.html"],
  "2026-aime-i-6": ["Exponents", "https://saintlymath.com/exponents.html"],
  "2026-aime-i-7": ["Counting", "https://saintlymath.com/counting.html"],
  "2026-aime-i-8": ["Modular Arithmetic", "https://saintlymath.com/modular%20arithmetic.html"],
  "2026-aime-i-9": ["Casework", "https://saintlymath.com/casework.html"],
  "2026-aime-ii-1": ["Series", "https://saintlymath.com/series.html"],
  "2026-aime-ii-10": ["Similar Triangles", "https://saintlymath.com/similar%20triangles.html"],
  "2026-aime-ii-11": ["Factoring", "https://saintlymath.com/factoring.html"],
  "2026-aime-ii-14": ["Casework", "https://saintlymath.com/casework.html"],
  "2026-aime-ii-15": ["Modular Arithmetic", "https://saintlymath.com/modular%20arithmetic.html"],
  "2026-aime-ii-2": ["Counting", "https://saintlymath.com/counting.html"],
  "2026-aime-ii-5": ["Counting", "https://saintlymath.com/counting.html"],
  "2026-aime-ii-6": ["Functions And Graphing", "https://saintlymath.com/functions%20and%20graphing.html"],
  "2026-aime-ii-7": ["Casework", "https://saintlymath.com/casework.html"],
  "2026-aime-ii-8": ["Similar Triangles", "https://saintlymath.com/similar%20triangles.html"],
  "2026-aime-ii-9": ["Series", "https://saintlymath.com/series.html"],
};

export type SaintlyLink = { topic: string; url: string };

/** The matching article for a problem, or null when nothing fits it. */
export function saintlyLinkFor(problemId: string): SaintlyLink | null {
  const hit = LINKS[problemId];
  return hit ? { topic: hit[0], url: hit[1] } : null;
}
